### ISSUE TITLE
Login Page 

### ISSUE THREAD

**Issue by bislara** [CYBORG-NIT-ROURKELA/project-sirius#4]
## Description
Make the frontend as well as the backend for the login page with email id and password as parameters and proper validation of every field in frontend as well as in the backend API

IMP - Write or send a photo of the table schema in the comments of this issue and once verified, go ahead to work on that.

## Deadline 
15th October, 9 PM

**Comment by bislara** [comment]
@irsayvid  Also, write code for check login and logout.

**Comment by irsayvid** [comment]
Admin: 
1. admin_id  (int)
2. name (tiny text)
3. email (varchar 100)
4. password (tiny text)
5. event_name (varchar 255)
6. event_description (long text)
7. event_date (varchar 150)
8. event_organiser (medium text)

User:
1. user_id (int)
2. user_name (tiny text)
3. email (varchar 100)
4. rating (long text)
5. comments_abt_event (long text)
6. suggestions (long_text)
7. admin_fk (foreign key admin_id)

Template_preview:
1. id (int)
2. font_size (smallcint)
3. font_color (varchar 50)
4. x_coordinate (int)
5. y_coordinate (int)
6. font_type (varchar 50)
7. admin_fk (foreign key admin_id)
