### ISSUE TITLE
Change date time field

### ISSUE THREAD

**Issue by irsayvid** [CYBORG-NIT-ROURKELA/project-sirius#65]
**Describe the bug**
Change date time field from text to date time picker

**Expected behavior**
It should show calendar view with future dates as well as past. The time field should be in the same format as the placeholder of input

**Comment by Rishi22-Coding** [comment]
I want to work on this issue please assign me

**Comment by irsayvid** [comment]
Sure go ahead!

**Comment by Rishi22-Coding** [comment]
@irsayvid can you please elaborate where i should change that. I mean in which file?

**Comment by irsayvid** [comment]
events.html
There'll be a modal which pops up on clicking update

**Comment by Rishi22-Coding** [comment]
okay got it

**Comment by Rishi22-Coding** [comment]
@irsayvid hey what do you think??
