### ISSUE TITLE
Can't switch back to HomePage while on Contact Page

### ISSUE THREAD

**Issue by mohit01-beep** [CYBORG-NIT-ROURKELA/project-sirius#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I was on contacts page and there home icon was showing in upper left corner of site but when i tried to click on it to go back it wasn't clicking.
I think you didn't put <a> tag over it yet.
I attached screenshot for refrence
**Screenshots**
![image](https://user-images.githubusercontent.com/59441111/136061595-41921b61-03b9-4068-b47a-390c84ad5ba0.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8]
 - Browser [firefox]

**Additional context**

**Comment by irsayvid** [comment]
No issues, I'll fix that from my side

**Comment by mohit01-beep** [comment]
Yea it worked Congo
